import { ADDITIONAL_CALCULATORS } from './additional-calculators';

export type CalculatorCategory =
  | 'business-finance'
  | 'loans'
  | 'taxes-pricing'
  | 'payments'
  | 'freelance'
  | 'inventory';

export interface CalculatorDefinition {
  slug: string;
  name: string;
  category: CalculatorCategory;
  title: string;
  description: string;
  keywords: string[];
  formula?: string;
  howItWorks?: string;
  notes?: string[];
  related?: string[];
}

export const CALCULATOR_REGISTRY: readonly CalculatorDefinition[] = [
  {
    slug: 'break-even-sales-calculator', name: 'Break-Even Point Calculator', category: 'business-finance', title: 'Break-Even Point Calculator — Units & Revenue | X-Facture', description: 'Calculate break-even units, break-even revenue and contribution margin for a business.', keywords: ['break-even calculator', 'break even point', 'break-even units', 'break-even revenue', 'contribution margin'], formula: 'Break-even units = Fixed costs ÷ (Selling price per unit − Variable cost per unit). Break-even revenue = Break-even units × Selling price.', howItWorks: 'The calculator finds the sales volume where contribution from each unit exactly covers fixed costs. It also shows the contribution margin so you can see how pricing and variable costs affect the break-even point.', notes: ['Break-even units are rounded up to the next whole unit.', 'The model assumes one selling price and one variable cost per unit.', 'A non-positive contribution margin cannot produce a finite break-even point.'], related: ['gross-margin-markup-calculator', 'cash-burn-runway-calculator', 'hourly-freelance-rate-calculator']
  },
  {
    slug: 'cash-burn-runway-calculator', name: 'Cash Burn & Runway Calculator', category: 'business-finance', title: 'Cash Burn & Runway Calculator | X-Facture', description: 'Calculate monthly cash burn, business runway and projected cash depletion from revenue and expenses.', keywords: ['cash burn calculator', 'runway calculator', 'startup runway', 'cash flow runway', 'burn rate'], formula: 'Net burn = Monthly expenses − Monthly revenue. Runway is the modeled time until projected cash reaches zero.', howItWorks: 'Starting cash is projected month by month using revenue, operating expenses and the planned revenue growth rate. The result shows both the current burn rate and the modeled cash-depletion horizon.', notes: ['This is a planning model, not a cash-flow statement.', 'Revenue growth is applied before each month’s net cash flow.', 'If modeled monthly cash flow remains non-negative, runway is shown as unlimited.'], related: ['break-even-sales-calculator', 'compound-working-capital-calculator', 'inventory-turnover-holding-calculator']
  },
  {
    slug: 'cash-register-change-calculator', name: 'Cash Register Change Calculator', category: 'business-finance', title: 'Cash Register Change Calculator | X-Facture', description: 'Calculate customer change and an efficient cash denomination breakdown for a transaction.', keywords: ['change calculator', 'cash register calculator', 'cash change', 'denomination calculator'], formula: 'Change due = Amount tendered − Sale total. Denominations are selected greedily from the largest available value downward.', howItWorks: 'Enter the sale total and the cash received. The calculator determines the amount due back and breaks it into common bills and coins for quick cashier use.', notes: ['The current denomination set is US dollar based.', 'Insufficient tender produces a short-payment state rather than a negative change amount.', 'Cash denominations can be localized in a future currency profile.'], related: ['sales-tax-vat-splitter', 'gross-margin-markup-calculator', 'stripe-paypal-fee-calculator']
  },
  {
    slug: 'commercial-loan-emi-calculator', name: 'Commercial Loan EMI Calculator', category: 'loans', title: 'Commercial Loan EMI Calculator | X-Facture', description: 'Estimate commercial loan payments, total interest and repayment cost from loan terms.', keywords: ['commercial loan calculator', 'business loan EMI', 'loan payment calculator', 'loan interest calculator'], formula: 'Payment = P × r × (1 + r)^n ÷ ((1 + r)^n − 1), where P is principal, r is the monthly rate and n is the number of payments.', howItWorks: 'The calculator converts the annual nominal rate to a monthly rate and solves the standard fixed-payment amortization formula. It then separates total repayment into principal and interest.', notes: ['A zero-interest loan is handled as principal divided by the number of payments.', 'Actual lender payments may differ because of fees, insurance, compounding conventions or payment timing.', 'The displayed EMI is an estimate, not a credit offer.'], related: ['cash-burn-runway-calculator', 'compound-working-capital-calculator', 'sales-tax-vat-splitter']
  },
  {
    slug: 'compound-working-capital-calculator', name: 'Compound Interest & Contribution Calculator', category: 'business-finance', title: 'Compound Interest Calculator with Monthly Contributions | X-Facture', description: 'Project future value from starting capital, recurring monthly contributions, an annual return and a time horizon.', keywords: ['compound interest calculator', 'compound growth calculator', 'investment growth calculator', 'future value calculator', 'monthly contribution calculator'], formula: 'Future value = P(1 + r)^n + PMT × ((1 + r)^n − 1) ÷ r, using monthly compounding and end-of-month contributions.', howItWorks: 'Starting capital compounds each month while recurring contributions are added over the selected period. The result separates contributed capital from modeled growth so the effect of compounding is visible.', notes: ['The current model uses monthly compounding.', 'Recurring contributions are treated as end-of-month contributions.', 'The selected return is an assumption and is not a guaranteed investment return.'], related: ['cash-burn-runway-calculator', 'inventory-turnover-holding-calculator', 'commercial-loan-emi-calculator']
  },
  {
    slug: 'currency-exchange-fee-calculator', name: 'Currency Exchange Fee Calculator', category: 'payments', title: 'Currency Exchange Fee Calculator | X-Facture', description: 'Calculate exchange fees, effective exchange rates and the real cost of converting currencies.', keywords: ['currency exchange calculator', 'exchange fee calculator', 'FX fee', 'effective exchange rate'], formula: 'FX markup = Mid-market value − Offered-rate value. Total conversion cost = FX markup + fixed fees.', howItWorks: 'Enter the amount being converted, the mid-market reference rate, the provider’s offered rate and any fixed fee. The calculator estimates the value lost to the rate spread and explicit charges.', notes: ['The direction of the exchange rate matters: both rates must quote the same source and target currencies.', 'The model treats the difference between reference and offered rates as an exchange markup.', 'Provider pricing can vary by amount, corridor and payment method.'], related: ['stripe-paypal-fee-calculator', 'sales-tax-vat-splitter', 'cash-register-change-calculator']
  },
  {
    slug: 'gross-margin-markup-calculator', name: 'Gross Margin & Markup Calculator', category: 'taxes-pricing', title: 'Gross Margin vs Markup Calculator | X-Facture', description: 'Convert between gross margin and markup, calculate selling price from cost and estimate product profit.', keywords: ['gross margin calculator', 'markup calculator', 'margin vs markup', 'COGS calculator', 'selling price calculator'], formula: 'Gross margin = (Selling price − Cost) ÷ Selling price. Markup = (Selling price − Cost) ÷ Cost. Target-price formula: Price = Cost ÷ (1 − Margin).', howItWorks: 'Use target-margin mode to solve for the selling price, or price-analysis mode to calculate the margin and markup implied by a selling price. Quantity inputs extend the result to total revenue and profit.', notes: ['Margin and markup are different percentages with different denominators.', 'Target margins approaching 100% create very large selling prices.', 'The calculator uses product cost as COGS and does not include operating expenses unless they are embedded in the cost input.'], related: ['break-even-sales-calculator', 'sales-tax-vat-splitter', 'hourly-freelance-rate-calculator']
  },
  {
    slug: 'hourly-freelance-rate-calculator', name: 'Freelance Hourly Rate Calculator', category: 'freelance', title: 'Freelance Hourly Rate Calculator | X-Facture', description: 'Calculate a sustainable freelance hourly rate from income goals, expenses, taxes and billable hours.', keywords: ['freelance rate calculator', 'hourly rate calculator', 'freelancer pricing', 'freelance income calculator'], formula: 'Required gross income = Net income ÷ (1 − tax rate). Required revenue = Gross income + overhead, adjusted by the profit buffer. Hourly rate = Required revenue ÷ annual billable hours.', howItWorks: 'The model starts with the freelancer’s desired take-home income, reserves an estimated tax amount, adds annual overhead and a business buffer, then divides the required revenue by realistic billable hours.', notes: ['Tax rates are user assumptions and are not jurisdiction-specific tax advice.', 'Billable hours exclude non-billable sales, administration and downtime.', 'The displayed day rate is based on an 8-hour day.'], related: ['gross-margin-markup-calculator', 'break-even-sales-calculator', 'cash-burn-runway-calculator']
  },
  {
    slug: 'inventory-turnover-holding-calculator', name: 'Inventory Turnover & Holding Calculator', category: 'inventory', title: 'Inventory Turnover & Holding Cost Calculator | X-Facture', description: 'Calculate inventory turnover, days inventory outstanding and inventory holding costs.', keywords: ['inventory turnover calculator', 'inventory holding cost', 'inventory days', 'stock turnover'], formula: 'Inventory turnover = Annual COGS ÷ Average inventory. Days inventory = 365 ÷ Turnover. Annual holding cost = Average inventory × Holding-cost rate.', howItWorks: 'Enter annual cost of goods sold, average inventory and an estimated annual carrying-cost rate. The calculator translates those inputs into turnover speed, inventory days and annual carrying cost.', notes: ['Average inventory is preferable to ending inventory when the data is available.', 'The holding-cost rate is an assumption covering the carrying costs relevant to the business.', 'The cost breakdown displayed by the chart is an illustrative allocation, not an accounting classification.'], related: ['break-even-sales-calculator', 'cash-burn-runway-calculator', 'gross-margin-markup-calculator']
  },
  {
    slug: 'late-fee-interest-calculator', name: 'Late Fee & Interest Calculator', category: 'taxes-pricing', title: 'Late Fee & Interest Calculator | X-Facture', description: 'Calculate late payment fees and interest on overdue invoices or balances.', keywords: ['late fee calculator', 'late payment interest', 'invoice interest calculator', 'overdue invoice calculator'], formula: 'Daily rate = Annual rate ÷ 365. With daily compounding, interest = Principal × ((1 + daily rate)^overdue days − 1).', howItWorks: 'The calculator removes any grace period, applies the selected annual rate to the billable overdue days and adds a flat late fee when applicable. It also projects penalty amounts at 30, 60 and 90 days.', notes: ['Late-fee and interest rules vary by contract and jurisdiction.', 'Daily compounding is a modeling assumption and may not match the governing agreement.', 'Use the result as an estimate and verify the applicable legal or contractual terms.'], related: ['sales-tax-vat-splitter', 'stripe-paypal-fee-calculator', 'cash-burn-runway-calculator']
  },
  {
    slug: 'sales-tax-vat-splitter', name: 'Sales Tax & VAT Splitter', category: 'taxes-pricing', title: 'Sales Tax & VAT Calculator | X-Facture', description: 'Calculate tax-inclusive and tax-exclusive prices and split sales tax or VAT from a total.', keywords: ['VAT calculator', 'sales tax calculator', 'VAT inclusive', 'VAT exclusive', 'tax splitter'], formula: 'Tax added to net: Tax = Net × rate; Gross = Net + Tax. Tax extracted from gross: Net = Gross ÷ (1 + rate); Tax = Gross − Net.', howItWorks: 'Choose whether your entered amount already includes tax. The calculator either adds tax to a pre-tax amount or extracts the tax portion from a tax-inclusive total.', notes: ['A single percentage rate does not model progressive income taxes.', 'Tax rates differ by jurisdiction, product, customer and transaction type.', 'Country presets are reference examples and should be verified before filing or invoicing.'], related: ['gross-margin-markup-calculator', 'stripe-paypal-fee-calculator', 'late-fee-interest-calculator']
  },
  {
    slug: 'stripe-paypal-fee-calculator', name: 'Stripe & PayPal Fee Calculator', category: 'payments', title: 'Stripe & PayPal Fee Calculator | X-Facture', description: 'Estimate payment processing fees, net payout and the amount to charge to receive a target amount.', keywords: ['Stripe fee calculator', 'PayPal fee calculator', 'payment processing fee', 'net payout calculator'], formula: 'Processing fee = Gross amount × percentage rate + fixed fee. Target gross = (Target net + fixed fee) ÷ (1 − percentage rate).', howItWorks: 'Choose a processing-fee preset or enter custom rates. The calculator can work forward from a customer charge to the merchant payout or reverse the formula to find the charge needed for a target net amount.', notes: ['Processor pricing varies by country, payment method, currency and account type.', 'Presets are estimates and should be checked against the processor’s current pricing.', 'The calculator does not model every processor surcharge or dispute fee.'], related: ['currency-exchange-fee-calculator', 'sales-tax-vat-splitter', 'cash-register-change-calculator']
  },
  ...ADDITIONAL_CALCULATORS,
] as const;

export function getCalculatorBySlug(slug: string): CalculatorDefinition | undefined {
  return CALCULATOR_REGISTRY.find(calculator => calculator.slug === slug);
}
