export interface GeoLocation {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  flag: string;
  latitude: number;
  longitude: number;
  timezone: string;
  elevationMeters?: number;
  isCustom?: boolean;
  tier?: number; // 1 = major world hub (always visible), 2 = capital/continental hub, 3 = regional clock
}

export const PRESET_LOCATIONS: GeoLocation[] = [
  // --- ASIA PACIFIC ---
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    elevationMeters: 40,
    tier: 1
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    flag: '🇰🇷',
    latitude: 37.5665,
    longitude: 126.9780,
    timezone: 'Asia/Seoul',
    elevationMeters: 38,
    tier: 1
  },
  {
    id: 'beijing',
    name: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    flag: '🇨🇳',
    latitude: 39.9042,
    longitude: 116.4074,
    timezone: 'Asia/Shanghai',
    elevationMeters: 43,
    tier: 1
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    flag: '🇨🇳',
    latitude: 31.2304,
    longitude: 121.4737,
    timezone: 'Asia/Shanghai',
    elevationMeters: 4,
    tier: 1
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    flag: '🇭🇰',
    latitude: 22.3193,
    longitude: 114.1694,
    timezone: 'Asia/Hong_Kong',
    elevationMeters: 30,
    tier: 1
  },
  {
    id: 'taipei',
    name: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    flag: '🇹🇼',
    latitude: 25.0330,
    longitude: 121.5654,
    timezone: 'Asia/Taipei',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    flag: '🇸🇬',
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: 'Asia/Singapore',
    elevationMeters: 15,
    tier: 1
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    flag: '🇹🇭',
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: 'Asia/Bangkok',
    elevationMeters: 2,
    tier: 1
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    flag: '🇻🇳',
    latitude: 21.0285,
    longitude: 105.8542,
    timezone: 'Asia/Ho_Chi_Minh',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    flag: '🇲🇾',
    latitude: 3.1390,
    longitude: 101.6869,
    timezone: 'Asia/Kuala_Lumpur',
    elevationMeters: 66,
    tier: 2
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    flag: '🇮🇩',
    latitude: -6.2088,
    longitude: 106.8456,
    timezone: 'Asia/Jakarta',
    elevationMeters: 8,
    tier: 1
  },
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    flag: '🇵🇭',
    latitude: 14.5995,
    longitude: 120.9842,
    timezone: 'Asia/Manila',
    elevationMeters: 7,
    tier: 1
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    latitude: 19.0760,
    longitude: 72.8777,
    timezone: 'Asia/Kolkata',
    elevationMeters: 14,
    tier: 1
  },
  {
    id: 'delhi',
    name: 'New Delhi',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    latitude: 28.6139,
    longitude: 77.2090,
    timezone: 'Asia/Kolkata',
    elevationMeters: 216,
    tier: 1
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: 'Asia/Kolkata',
    elevationMeters: 920,
    tier: 2
  },
  {
    id: 'karachi',
    name: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    flag: '🇵🇰',
    latitude: 24.8607,
    longitude: 67.0011,
    timezone: 'Asia/Karachi',
    elevationMeters: 10,
    tier: 1
  },
  {
    id: 'dhaka',
    name: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    flag: '🇧🇩',
    latitude: 23.8103,
    longitude: 90.4125,
    timezone: 'Asia/Dhaka',
    elevationMeters: 4,
    tier: 2
  },
  {
    id: 'kathmandu',
    name: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    latitude: 27.7172,
    longitude: 85.3240,
    timezone: 'Asia/Kathmandu',
    elevationMeters: 1400,
    tier: 2
  },
  {
    id: 'colombo',
    name: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    flag: '🇱🇰',
    latitude: 6.9271,
    longitude: 79.8612,
    timezone: 'Asia/Colombo',
    elevationMeters: 7,
    tier: 2
  },
  {
    id: 'tashkent',
    name: 'Tashkent',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    flag: '🇺🇿',
    latitude: 41.2995,
    longitude: 69.2401,
    timezone: 'Asia/Tashkent',
    elevationMeters: 450,
    tier: 2
  },
  {
    id: 'almaty',
    name: 'Almaty',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    flag: '🇰🇿',
    latitude: 43.2220,
    longitude: 76.8512,
    timezone: 'Asia/Almaty',
    elevationMeters: 785,
    tier: 2
  },

  // --- OCEANIA ---
  {
    id: 'canberra',
    name: 'Canberra',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -35.2809,
    longitude: 149.1300,
    timezone: 'Australia/Sydney',
    elevationMeters: 580,
    tier: 1
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
    elevationMeters: 19,
    tier: 1
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -37.8136,
    longitude: 144.9631,
    timezone: 'Australia/Melbourne',
    elevationMeters: 31,
    tier: 2
  },
  {
    id: 'brisbane',
    name: 'Brisbane',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -27.4698,
    longitude: 153.0251,
    timezone: 'Australia/Brisbane',
    elevationMeters: 28,
    tier: 2
  },
  {
    id: 'perth',
    name: 'Perth',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -31.9505,
    longitude: 115.8605,
    timezone: 'Australia/Perth',
    elevationMeters: 15,
    tier: 1
  },
  {
    id: 'adelaide',
    name: 'Adelaide',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -34.9285,
    longitude: 138.6007,
    timezone: 'Australia/Adelaide',
    elevationMeters: 50,
    tier: 2
  },
  {
    id: 'darwin',
    name: 'Darwin',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    latitude: -12.4634,
    longitude: 130.8456,
    timezone: 'Australia/Darwin',
    elevationMeters: 31,
    tier: 2
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    flag: '🇳🇿',
    latitude: -36.8485,
    longitude: 174.7633,
    timezone: 'Pacific/Auckland',
    elevationMeters: 20,
    tier: 1
  },
  {
    id: 'wellington',
    name: 'Wellington',
    country: 'New Zealand',
    countryCode: 'NZ',
    flag: '🇳🇿',
    latitude: -41.2865,
    longitude: 174.7762,
    timezone: 'Pacific/Auckland',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'suva',
    name: 'Suva',
    country: 'Fiji',
    countryCode: 'FJ',
    flag: '🇫🇯',
    latitude: -18.1416,
    longitude: 178.4419,
    timezone: 'Pacific/Fiji',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'honolulu',
    name: 'Honolulu',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 21.3069,
    longitude: -157.8583,
    timezone: 'Pacific/Honolulu',
    elevationMeters: 6,
    tier: 1
  },
  {
    id: 'tahiti',
    name: 'Papeete',
    country: 'French Polynesia',
    countryCode: 'PF',
    flag: '🇵🇫',
    latitude: -17.5516,
    longitude: -149.5585,
    timezone: 'Pacific/Tahiti',
    elevationMeters: 5,
    tier: 2
  },

  // --- EUROPE ---
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    elevationMeters: 25,
    tier: 1
  },
  {
    id: 'dublin',
    name: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    flag: '🇮🇪',
    latitude: 53.3498,
    longitude: -6.2603,
    timezone: 'Europe/Dublin',
    elevationMeters: 15,
    tier: 2
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    elevationMeters: 35,
    tier: 1
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    latitude: 52.5200,
    longitude: 13.4050,
    timezone: 'Europe/Berlin',
    elevationMeters: 34,
    tier: 1
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    latitude: 52.3676,
    longitude: 4.9041,
    timezone: 'Europe/Amsterdam',
    elevationMeters: 2,
    tier: 2
  },
  {
    id: 'brussels',
    name: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    flag: '🇧🇪',
    latitude: 50.8503,
    longitude: 4.3517,
    timezone: 'Europe/Brussels',
    elevationMeters: 13,
    tier: 2
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    latitude: 40.4168,
    longitude: -3.7038,
    timezone: 'Europe/Madrid',
    elevationMeters: 667,
    tier: 1
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    latitude: 38.7223,
    longitude: -9.1393,
    timezone: 'Europe/Lisbon',
    elevationMeters: 15,
    tier: 2
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: 'Europe/Rome',
    elevationMeters: 21,
    tier: 1
  },
  {
    id: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    flag: '🇨🇭',
    latitude: 47.3769,
    longitude: 8.5417,
    timezone: 'Europe/Zurich',
    elevationMeters: 408,
    tier: 2
  },
  {
    id: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    flag: '🇦🇹',
    latitude: 48.2082,
    longitude: 16.3738,
    timezone: 'Europe/Vienna',
    elevationMeters: 171,
    tier: 2
  },
  {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    flag: '🇵🇱',
    latitude: 52.2297,
    longitude: 21.0122,
    timezone: 'Europe/Warsaw',
    elevationMeters: 110,
    tier: 2
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    flag: '🇸🇪',
    latitude: 59.3293,
    longitude: 18.0686,
    timezone: 'Europe/Stockholm',
    elevationMeters: 28,
    tier: 2
  },
  {
    id: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    flag: '🇳🇴',
    latitude: 59.9139,
    longitude: 10.7522,
    timezone: 'Europe/Oslo',
    elevationMeters: 23,
    tier: 2
  },
  {
    id: 'helsinki',
    name: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    flag: '🇫🇮',
    latitude: 60.1699,
    longitude: 24.9384,
    timezone: 'Europe/Helsinki',
    elevationMeters: 25,
    tier: 2
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    flag: '🇩🇰',
    latitude: 55.6761,
    longitude: 12.5683,
    timezone: 'Europe/Copenhagen',
    elevationMeters: 14,
    tier: 2
  },
  {
    id: 'athens',
    name: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    flag: '🇬🇷',
    latitude: 37.9838,
    longitude: 23.7275,
    timezone: 'Europe/Athens',
    elevationMeters: 70,
    tier: 2
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    flag: '🇹🇷',
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: 'Europe/Istanbul',
    elevationMeters: 40,
    tier: 1
  },
  {
    id: 'kyiv',
    name: 'Kyiv',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    latitude: 50.4501,
    longitude: 30.5234,
    timezone: 'Europe/Kyiv',
    elevationMeters: 179,
    tier: 2
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    latitude: 55.7558,
    longitude: 37.6173,
    timezone: 'Europe/Moscow',
    elevationMeters: 156,
    tier: 1
  },
  {
    id: 'reykjavik',
    name: 'Reykjavík',
    country: 'Iceland',
    countryCode: 'IS',
    flag: '🇮🇸',
    latitude: 64.1466,
    longitude: -21.9426,
    timezone: 'Atlantic/Reykjavik',
    elevationMeters: 15,
    tier: 1
  },
  {
    id: 'tromso',
    name: 'Tromsø',
    country: 'Norway',
    countryCode: 'NO',
    flag: '🇳🇴',
    latitude: 69.6492,
    longitude: 18.9553,
    timezone: 'Europe/Oslo',
    elevationMeters: 20,
    tier: 2
  },

  // --- MIDDLE EAST & AFRICA ---
  {
    id: 'ankara',
    name: 'Ankara',
    country: 'Turkey',
    countryCode: 'TR',
    flag: '🇹🇷',
    latitude: 39.9334,
    longitude: 32.8597,
    timezone: 'Europe/Istanbul',
    elevationMeters: 938,
    tier: 1
  },
  {
    id: 'abu-dhabi',
    name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    latitude: 24.4539,
    longitude: 54.3773,
    timezone: 'Asia/Dubai',
    elevationMeters: 7,
    tier: 1
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    elevationMeters: 5,
    tier: 1
  },
  {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    latitude: 24.7136,
    longitude: 46.6753,
    timezone: 'Asia/Riyadh',
    elevationMeters: 612,
    tier: 1
  },
  {
    id: 'doha',
    name: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    flag: '🇶🇦',
    latitude: 25.2854,
    longitude: 51.5310,
    timezone: 'Asia/Qatar',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'tehran',
    name: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    flag: '🇮🇷',
    latitude: 35.6892,
    longitude: 51.3890,
    timezone: 'Asia/Tehran',
    elevationMeters: 1200,
    tier: 1
  },
  {
    id: 'jerusalem',
    name: 'Jerusalem',
    country: 'Israel',
    countryCode: 'IL',
    flag: '🇮🇱',
    latitude: 31.7683,
    longitude: 35.2137,
    timezone: 'Asia/Jerusalem',
    elevationMeters: 754,
    tier: 2
  },
  {
    id: 'beirut',
    name: 'Beirut',
    country: 'Lebanon',
    countryCode: 'LB',
    flag: '🇱🇧',
    latitude: 33.8938,
    longitude: 35.5018,
    timezone: 'Asia/Beirut',
    elevationMeters: 20,
    tier: 2
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    flag: '🇪🇬',
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: 'Africa/Cairo',
    elevationMeters: 23,
    tier: 1
  },
  {
    id: 'rabat',
    name: 'Rabat',
    country: 'Morocco',
    countryCode: 'MA',
    flag: '🇲🇦',
    latitude: 34.0209,
    longitude: -6.8416,
    timezone: 'Africa/Casablanca',
    elevationMeters: 53,
    tier: 1
  },
  {
    id: 'casablanca',
    name: 'Casablanca',
    country: 'Morocco',
    countryCode: 'MA',
    flag: '🇲🇦',
    latitude: 33.5731,
    longitude: -7.5898,
    timezone: 'Africa/Casablanca',
    elevationMeters: 20,
    tier: 1
  },
  {
    id: 'dakar',
    name: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    flag: '🇸🇳',
    latitude: 14.7167,
    longitude: -17.4677,
    timezone: 'Africa/Dakar',
    elevationMeters: 22,
    tier: 2
  },
  {
    id: 'lagos',
    name: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    flag: '🇳🇬',
    latitude: 6.5244,
    longitude: 3.3792,
    timezone: 'Africa/Lagos',
    elevationMeters: 10,
    tier: 1
  },
  {
    id: 'accra',
    name: 'Accra',
    country: 'Ghana',
    countryCode: 'GH',
    flag: '🇬🇭',
    latitude: 5.6037,
    longitude: -0.1870,
    timezone: 'Africa/Accra',
    elevationMeters: 61,
    tier: 2
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    flag: '🇰🇪',
    latitude: -1.2921,
    longitude: 36.8219,
    timezone: 'Africa/Nairobi',
    elevationMeters: 1795,
    tier: 1
  },
  {
    id: 'addis-ababa',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    flag: '🇪🇹',
    latitude: 9.0320,
    longitude: 38.7469,
    timezone: 'Africa/Addis_Ababa',
    elevationMeters: 2355,
    tier: 2
  },
  {
    id: 'pretoria',
    name: 'Pretoria',
    country: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    latitude: -25.7479,
    longitude: 28.2293,
    timezone: 'Africa/Johannesburg',
    elevationMeters: 1339,
    tier: 1
  },
  {
    id: 'johannesburg',
    name: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    latitude: -26.2041,
    longitude: 28.0473,
    timezone: 'Africa/Johannesburg',
    elevationMeters: 1753,
    tier: 1
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    latitude: -33.9249,
    longitude: 18.4241,
    timezone: 'Africa/Johannesburg',
    elevationMeters: 25,
    tier: 1
  },

  // --- NORTH AMERICA ---
  {
    id: 'washington-dc',
    name: 'Washington, D.C.',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 38.9072,
    longitude: -77.0369,
    timezone: 'America/New_York',
    elevationMeters: 20,
    tier: 1
  },
  {
    id: 'ottawa',
    name: 'Ottawa',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 45.4215,
    longitude: -75.6972,
    timezone: 'America/Toronto',
    elevationMeters: 70,
    tier: 1
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    elevationMeters: 10,
    tier: 1
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: 'America/Los_Angeles',
    elevationMeters: 89,
    tier: 1
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: 'America/Chicago',
    elevationMeters: 181,
    tier: 1
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: 'America/Los_Angeles',
    elevationMeters: 16,
    tier: 1
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 47.6062,
    longitude: -122.3321,
    timezone: 'America/Los_Angeles',
    elevationMeters: 53,
    tier: 2
  },
  {
    id: 'denver',
    name: 'Denver',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 39.7392,
    longitude: -104.9903,
    timezone: 'America/Denver',
    elevationMeters: 1609,
    tier: 2
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 33.4484,
    longitude: -112.0740,
    timezone: 'America/Phoenix',
    elevationMeters: 331,
    tier: 2
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 25.7617,
    longitude: -80.1918,
    timezone: 'America/New_York',
    elevationMeters: 2,
    tier: 2
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
    elevationMeters: 76,
    tier: 1
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 49.2827,
    longitude: -123.1207,
    timezone: 'America/Vancouver',
    elevationMeters: 70,
    tier: 1
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 45.5017,
    longitude: -73.5673,
    timezone: 'America/Toronto',
    elevationMeters: 36,
    tier: 2
  },
  {
    id: 'calgary',
    name: 'Calgary',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 51.0447,
    longitude: -114.0719,
    timezone: 'America/Edmonton',
    elevationMeters: 1045,
    tier: 2
  },
  {
    id: 'halifax',
    name: 'Halifax',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 44.6488,
    longitude: -63.5752,
    timezone: 'America/Halifax',
    elevationMeters: 45,
    tier: 2
  },
  {
    id: 'st-johns',
    name: "St. John's",
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    latitude: 47.5615,
    longitude: -52.7126,
    timezone: 'America/St_Johns',
    elevationMeters: 140,
    tier: 2
  },
  {
    id: 'anchorage',
    name: 'Anchorage',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    latitude: 61.2181,
    longitude: -149.9003,
    timezone: 'America/Anchorage',
    elevationMeters: 31,
    tier: 1
  },
  {
    id: 'nuuk',
    name: 'Nuuk',
    country: 'Greenland',
    countryCode: 'GL',
    flag: '🇬🇱',
    latitude: 64.1814,
    longitude: -51.6941,
    timezone: 'America/Nuuk',
    elevationMeters: 5,
    tier: 2
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    flag: '🇲🇽',
    latitude: 19.4326,
    longitude: -99.1332,
    timezone: 'America/Mexico_City',
    elevationMeters: 2240,
    tier: 1
  },
  {
    id: 'panama-city',
    name: 'Panama City',
    country: 'Panama',
    countryCode: 'PA',
    flag: '🇵🇦',
    latitude: 8.9824,
    longitude: -79.5199,
    timezone: 'America/Panama',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'havana',
    name: 'Havana',
    country: 'Cuba',
    countryCode: 'CU',
    flag: '🇨🇺',
    latitude: 23.1136,
    longitude: -82.3666,
    timezone: 'America/Havana',
    elevationMeters: 59,
    tier: 2
  },

  // --- SOUTH AMERICA ---
  {
    id: 'brasilia',
    name: 'Brasília',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    latitude: -15.8267,
    longitude: -47.9218,
    timezone: 'America/Sao_Paulo',
    elevationMeters: 1172,
    tier: 1
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    latitude: -23.5505,
    longitude: -46.6333,
    timezone: 'America/Sao_Paulo',
    elevationMeters: 760,
    tier: 1
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    latitude: -22.9068,
    longitude: -43.1729,
    timezone: 'America/Sao_Paulo',
    elevationMeters: 10,
    tier: 2
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    flag: '🇦🇷',
    latitude: -34.6037,
    longitude: -58.3816,
    timezone: 'America/Argentina/Buenos_Aires',
    elevationMeters: 25,
    tier: 1
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    flag: '🇨🇱',
    latitude: -33.4489,
    longitude: -70.6693,
    timezone: 'America/Santiago',
    elevationMeters: 570,
    tier: 1
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    countryCode: 'CO',
    flag: '🇨🇴',
    latitude: 4.7110,
    longitude: -74.0721,
    timezone: 'America/Bogota',
    elevationMeters: 2640,
    tier: 1
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    flag: '🇵🇪',
    latitude: -12.0464,
    longitude: -77.0428,
    timezone: 'America/Lima',
    elevationMeters: 154,
    tier: 1
  },
  {
    id: 'caracas',
    name: 'Caracas',
    country: 'Venezuela',
    countryCode: 'VE',
    flag: '🇻🇪',
    latitude: 10.4806,
    longitude: -66.9036,
    timezone: 'America/Caracas',
    elevationMeters: 900,
    tier: 2
  },
  {
    id: 'montevideo',
    name: 'Montevideo',
    country: 'Uruguay',
    countryCode: 'UY',
    flag: '🇺🇾',
    latitude: -34.9011,
    longitude: -56.1645,
    timezone: 'America/Montevideo',
    elevationMeters: 43,
    tier: 2
  }
];
